version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: symphony_db
      DB_USER: root
      DB_PASS: Admin1234*
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: symphony_db
      MYSQL_ROOT_PASSWORD: Admin1234*
    ports:
      - "3308:3306"