services:
  - type: web
    name: symphony-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: mysql-symphony
      - key: DB_PORT
        value: 3307
      - key: DB_NAME
        value: symphony_db
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: Admin1234*

  - type: web
    name: mysql-symphony
    env: docker
    plan: free
    dockerfilePath: Dockerfile.mysql
    autoDeploy: false
    ports:
      - port: 3307
        protocol: tcp