services:
  - type: web
    name: symphony-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: IEYQgcuaBiFpyUudFHSnFXZpmZEmXkMl
    ports:
      - port: 8080
        protocol: tcp